/** Stable, machine-readable error codes shared by the API and the UI. */
export const ERROR_CODES = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Accounts
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_NAME_TAKEN: 'ACCOUNT_NAME_TAKEN',
  ACCOUNT_BUSY: 'ACCOUNT_BUSY',
  ACCOUNT_CREDENTIALS_MISSING: 'ACCOUNT_CREDENTIALS_MISSING',
  ACCOUNT_SHARE_RESTRICTED: 'ACCOUNT_SHARE_RESTRICTED',

  // Browser profiles
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_LOCKED: 'PROFILE_LOCKED',
  PROFILE_PATH_INVALID: 'PROFILE_PATH_INVALID',

  // Browser sessions
  BROWSER_ALREADY_RUNNING: 'BROWSER_ALREADY_RUNNING',
  BROWSER_NOT_RUNNING: 'BROWSER_NOT_RUNNING',
  BROWSER_LAUNCH_FAILED: 'BROWSER_LAUNCH_FAILED',
  BROWSER_CRASHED: 'BROWSER_CRASHED',

  // Automation
  AUTOMATION_TIMEOUT: 'AUTOMATION_TIMEOUT',
  AUTOMATION_FAILED: 'AUTOMATION_FAILED',
  AUTOMATION_NOT_LOGGED_IN: 'AUTOMATION_NOT_LOGGED_IN',
  AUTOMATION_SELECTOR_MISSING: 'AUTOMATION_SELECTOR_MISSING',
  AUTOMATION_BLOCKED: 'AUTOMATION_BLOCKED',
  AUTOMATION_LOGIN_FAILED: 'AUTOMATION_LOGIN_FAILED',
  AUTOMATION_GATED: 'AUTOMATION_GATED',

  // Operator input
  OPERATOR_INPUT_TIMEOUT: 'OPERATOR_INPUT_TIMEOUT',
  OPERATOR_INPUT_CANCELLED: 'OPERATOR_INPUT_CANCELLED',
  OPERATOR_REQUEST_NOT_FOUND: 'OPERATOR_REQUEST_NOT_FOUND',

  // Groups
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',

  // Jobs and queue
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_ALREADY_RUNNING: 'JOB_ALREADY_RUNNING',
  JOB_NOT_CANCELLABLE: 'JOB_NOT_CANCELLABLE',
  JOB_NOT_RETRYABLE: 'JOB_NOT_RETRYABLE',
  JOB_CANCELLED: 'JOB_CANCELLED',
  INVALID_JOB_TRANSITION: 'INVALID_JOB_TRANSITION',

  // Storage
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  PATH_TRAVERSAL: 'PATH_TRAVERSAL',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  WORKBOOK_INVALID: 'WORKBOOK_INVALID',

  // Settings
  SETTINGS_INVALID: 'SETTINGS_INVALID',

  // Login
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
