import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { SqliteConnection } from './connection.js';

const MIGRATIONS_TABLE = `
  CREATE TABLE IF NOT EXISTS __migrations (
    name TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL
  )
`;

/** Migration SQL generated by drizzle-kit lives next to the compiled output. */
export const migrationsDir = (): string =>
  join(dirname(fileURLToPath(import.meta.url)), 'migrations');

export interface MigrationResult {
  applied: string[];
  alreadyApplied: number;
}

/**
 * Applies every `.sql` file in order, once. Each file runs inside its own
 * transaction, so a failing migration leaves the database on the last good one
 * rather than half-changed.
 */
export const runMigrations = (
  connection: SqliteConnection,
  directory = migrationsDir(),
): MigrationResult => {
  connection.exec(MIGRATIONS_TABLE);

  const files = readdirSync(directory)
    .filter((name) => name.endsWith('.sql'))
    .sort();

  const applied = new Set(readApplied(connection));
  const freshlyApplied: string[] = [];

  for (const file of files) {
    if (applied.has(file)) continue;

    // drizzle-kit separates independent statements with this marker.
    const sql = readFileSync(join(directory, file), 'utf8');
    const statements = sql
      .split('--> statement-breakpoint')
      .map((statement) => statement.trim())
      .filter((statement) => statement.length > 0);

    connection.exec('BEGIN IMMEDIATE');
    try {
      for (const statement of statements) connection.exec(statement);
      connection.runSync(
        'INSERT INTO __migrations (name, applied_at) VALUES (?, ?)',
        file,
        new Date().toISOString(),
      );
      connection.exec('COMMIT');
    } catch (error) {
      connection.exec('ROLLBACK');
      throw new Error(`Migration ${file} failed: ${String(error)}`, { cause: error });
    }

    freshlyApplied.push(file);
  }

  return { applied: freshlyApplied, alreadyApplied: applied.size };
};

const readApplied = (connection: SqliteConnection): string[] =>
  connection.allSync<{ name: string }>('SELECT name FROM __migrations').map((row) => row.name);
